# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "966ecf2737d8dee020c04a0c80940dd3"
application_url = "https://baby-nascar-commands-ensuring.trycloudflare.com"
embedded = true
name = "development-app"

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://baby-nascar-commands-ensuring.trycloudflare.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
