# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8080a194096cb602f516d4bb1841df93"
name = "test-meta-new"
application_url = "https://wendy-listening-preventing-boc.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locations,read_products,write_products"

[auth]
redirect_urls = [
  "https://wendy-listening-preventing-boc.trycloudflare.com/auth/callback",
  "https://wendy-listening-preventing-boc.trycloudflare.com/auth/shopify/callback"
]

[build]
automatically_update_urls_on_dev = true
