// FILE: app/routes/app.jobs.types.ts

/**
 * Jobs route types.
 *
 * SECURITY CONTRACT:
 * - `status` must always be validated server-side against a strict enum.
 * - UI must treat unknown statuses as safe defaults (subdued).
 * - Dates must be ISO strings generated by the server (never client-provided).
 */

export const JOB_STATUSES = [
  "PENDING",
  "PROCESSING",
  "COMPLETED",
  "FAILED",
  "CANCELLED",
  "UNDONE",
] as const;

export type JobStatus = (typeof JOB_STATUSES)[number];

export interface JobRow {
  id: string;              // UUID v4 (validated server-side)
  bullJobId: string | null;
  productId: string;       // Shopify GID (server-owned)
  productTitle: string | null;
  status: JobStatus;
  progress: number;        // 0–100 (server-enforced clamp)
  costTokens: number;      // >= 0 (server-enforced)
  errorMessage: string | null;
  // Generation settings — populated at job creation, used in detail modal
  tone: string | null;     // maps from `vibe` column in DB
  format: string | null;
  // Description snapshot — populated by worker on COMPLETED
  generatedDescription: string | null;
  hasPreviousDescription: boolean; // true when DB `previousDescription` is non-null
  // Add these fields to the JobRow interface, after hasPreviousDescription:
draftBodyHtml: string;       // sanitized body_html from result JSON
metaTitle: string;           // meta_title from result JSON  
metaDescription: string;     // meta_description from result JSON
altTexts: { imageId: string; altText: string }[]; // from result JSON (if stored)
  createdAt: string;       // ISO string
  updatedAt: string;       // ISO string
}

export interface LoaderData {
  jobs: JobRow[];
  hasActiveJobs: boolean;
  hasNextPage: boolean;
  nextCursor: string | null;
  prevCursor: string | null;
  totalPending: number;    // server-computed, shop-scoped
  shopDomain: string;
}

/**
 * Polaris Badge tones allowed in this UI.
 * Keep narrow to avoid drift with Polaris API.
 */
export type BadgeTone =
  | "success"
  | "critical"
  | "attention"
  | "info"
  | "subdued"
  | "warning";

/**
 * Map status to UI badge metadata.
 * Fail-closed: unknown status → subdued.
 */
export function statusBadge(status: string): { label: string; tone: BadgeTone } {
  switch (status) {
    case "COMPLETED":
      return { label: "Completed", tone: "success" };
    case "FAILED":
      return { label: "Failed", tone: "critical" };
    case "PROCESSING":
      return { label: "Processing", tone: "info" };
    case "PENDING":
      return { label: "Pending", tone: "attention" };
    case "CANCELLED":
      return { label: "Cancelled", tone: "subdued" };
    case "UNDONE":
      return { label: "Undone", tone: "warning" };
    default:
      return { label: "Unknown", tone: "subdued" };
  }
}

/**
 * Runtime guard (use in server or UI before casting).
 */
export function isJobStatus(value: unknown): value is JobStatus {
  return typeof value === "string" && (JOB_STATUSES as readonly string[]).includes(value);
}

/**
 * Clamp progress defensively (UI-side safety).
 * Server must enforce authoritative bounds.
 */
export function clampProgress(value: unknown): number {
  const n = typeof value === "number" && Number.isFinite(value) ? value : 0;
  if (n <= 0) return 0;
  if (n >= 100) return 100;
  return Math.floor(n);
}