// FILE: app/routes/app.products.$productId.types.ts

/**
 * Product route types.
 *
 * SECURITY CONTRACT:
 * - `product.id` must be a Shopify Product GID (validated server-side).
 * - `ActiveJob.status` must be validated against strict enums (server-side).
 * - `DraftResult` is untrusted until server validates + sanitizes before persistence/apply.
 * - All timestamps are ISO strings generated by server.
 */

export const JOB_STATUSES = ["PENDING", "PROCESSING", "COMPLETED", "FAILED", "CANCELLED"] as const;
export type JobStatus = (typeof JOB_STATUSES)[number];

export interface ProductMeta {
  id: string; // gid://shopify/Product/...
  title: string;
  productType: string;
  vendor: string;
  tags: string[];
}

export interface ActiveJob {
  id: string; // UUID v4
  status: JobStatus;
}

/**
 * Draft output contract from LLM (DeepSeek).
 * NOTE: This is still untrusted input; validate with Zod on the server.
 */
export interface DraftResult {
  body_html?: string;
  meta_title?: string;
  meta_description?: string;
  keywords?: string[];
  primary_keyword?: string;
  headline?: string;
  social_caption?: string;
}

export interface LatestDraft {
  id: string; // UUID v4 (server-owned version id)
  createdAt: string; // ISO string
  isStale: boolean;
   result: DraftResult | null;
}

export interface CustomTemplate {
  id: string;
  name: string;
  instruction: string;
  createdAt: string;
}


export interface LoaderData {
  product: ProductMeta;
  descriptionHtml: string | null; // lazy-loaded by action intent fetch_description
  activeJob: ActiveJob | null;
  latestDraft: LatestDraft | null;
  policyWarnings: string[]; // server-produced warnings (safe strings)
   shopPlan: "free" | "basic" | "advanced" | "pro";
   customTemplates: CustomTemplate[];
}

// Action results are intentionally explicit and "tagged" by shape.
export type ActionResult =
  | { ok: true; kind: "generate"; jobId: string; status: "PENDING" }
  | { ok: true; kind: "apply"; applied: true }
  | { ok: true; kind: "suggest_keywords"; keywords: string[] }
  | { ok: true; kind: "fetch_description"; descriptionHtml: string; descriptionText: string }
  | { ok: true; kind: "create_template"; template: CustomTemplate }
  | { ok: true; kind: "delete_template" }  
  | { ok: false; kind: "error"; error: string; code?: string };

/**
 * Runtime guard helpers (UI/server can reuse).
 */
export function isJobStatus(value: unknown): value is JobStatus {
  return typeof value === "string" && (JOB_STATUSES as readonly string[]).includes(value);
}
